# version: "1.0"
# services:
#   whatabyte:
#     build: ./whatabyte-portal
#     ports:
#       - "8000:8000"
#     volumes:
#       - './whatabyte-portal:/app'
#       - /app/node_modules/

services:
  vue-project:
    build: ./vue-project
    ports:
      - "3003:3000"
    stdin_open: true
    tty: true
    volumes:
      - './vue-project:/app'
      - /app/node_modules